In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df["spam"] = df["Category"].apply(lambda x:1 if x == "spam" else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
pip install scikit-learn



  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/f1/7d/2e562207176a5dcdad513085670674bb11ffaf37e1393eacb6d7fb502481/scikit_learn-1.3.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.5.0 from https://files.pythonhosted.org/packages/06/15/e73734f9170b66c6a84a0bd7e03586e87e77404e2eb8e34749fc49fa43f7/scipy-1.11.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.1 kB ? eta -

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [12]:
x_train.shape

(4457,)

In [13]:
x_train.head()

663     Sorry me going home first... Daddy come fetch ...
1227    Reply with your name and address and YOU WILL ...
4887                               Or just do that 6times
288     hi baby im cruisin with my girl friend what r ...
1806      God bless.get good sleep my dear...i will pray!
Name: Message, dtype: object

In [14]:
x_train[4887]

'Or just do that 6times'

In [26]:
# count vectorizer

from sklearn.feature_extraction.text import CountVectorizer 

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7751 sparse matrix of type '<class 'numpy.int64'>'
	with 59175 stored elements in Compressed Sparse Row format>

In [25]:
x_train_cv.toarray()[:3][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
v.get_feature_names_out()[71]

'08700435505150p'

In [30]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [34]:
v.vocabulary_

{'sorry': 6339,
 'me': 4399,
 'going': 3175,
 'home': 3475,
 'first': 2869,
 'daddy': 2142,
 'come': 1902,
 'fetch': 2815,
 'later': 4036,
 'reply': 5725,
 'with': 7549,
 'your': 7718,
 'name': 4680,
 'and': 953,
 'address': 800,
 'you': 7713,
 'will': 7522,
 'receive': 5636,
 'by': 1583,
 'post': 5334,
 'weeks': 7451,
 'completely': 1929,
 'free': 2985,
 'accommodation': 766,
 'at': 1112,
 'various': 7260,
 'global': 3156,
 'locations': 4175,
 'www': 7646,
 'phb1': 5184,
 'com': 1896,
 'ph': 5182,
 '08700435505150p': 71,
 'or': 4972,
 'just': 3877,
 'do': 2377,
 'that': 6819,
 '6times': 588,
 'hi': 3426,
 'baby': 1187,
 'im': 3620,
 'cruisin': 2085,
 'my': 4663,
 'girl': 3142,
 'friend': 3005,
 'what': 7481,
 'up': 7186,
 'give': 3148,
 'call': 1600,
 'in': 3646,
 'hour': 3518,
 'if': 3605,
 'thats': 6821,
 'alright': 914,
 'fone': 2929,
 'on': 4932,
 'this': 6864,
 'now': 4838,
 'love': 4227,
 'jenny': 3815,
 'xxx': 7663,
 'god': 3168,
 'bless': 1385,
 'get': 3120,
 'good': 3188,
 's

In [39]:
x_train_np = x_train_cv.toarray()
x_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
np.where(x_train_np[0] != 0)

(array([1902, 2142, 2815, 2869, 3175, 3475, 4036, 4399, 6339], dtype=int64),)

In [42]:
x_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [45]:
x_train_np[0][3175]

1

In [47]:
from sklearn.naive_bayes  import MultinomialNB 

model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [48]:
x_test_cv = v.transform(x_test)

In [50]:
from sklearn.metrics  import classification_report

In [52]:
y_pred = model.predict(x_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.91      0.93       149

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [54]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [55]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [56]:
#pipeline
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [57]:
y_pred = clf.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.91      0.93       149

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
========================== Exercise ====================================

In [59]:
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier

In [104]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable

df = pd.read_csv("movies_sentiment_data.csv")
df = df[:1000]
df.head()

review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [105]:
#2. print the shape of the data
df.shape

(1000, 2)

In [106]:
#3. print top 5 datapoints
df.sentiment.value_counts()

sentiment
positive    527
negative    473
Name: count, dtype: int64

In [107]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df["Category"] = df["sentiment"].apply(lambda x: 1 if x == "positive" else 0)

In [108]:
df.head()

review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [109]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
df.Category.value_counts()

Category
1    527
0    473
Name: count, dtype: int64

In [110]:
#Do the 'train-test' splitting with test size of 20%
x_train, x_test, y_train, y_test = train_test_split(df.review, df.Category, test_size = 0.2)

In [112]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', RandomForestClassifier(n_estimators=50, criterion='entropy'))
])

In [113]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('nb',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

In [114]:
y_pred = clf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.62      0.69        96
           1       0.70      0.83      0.76       104

    accuracy                           0.73       200
   macro avg       0.74      0.73      0.73       200
weighted avg       0.74      0.73      0.73       200



In [115]:
#use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
clf1 = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', KNeighborsClassifier(n_neighbors=10, metric = 'euclidean'))
])

clf1.fit(x_train, y_train)
y_pred = clf1.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.47      0.33      0.39        96
           1       0.52      0.65      0.58       104

    accuracy                           0.50       200
   macro avg       0.49      0.49      0.48       200
weighted avg       0.49      0.50      0.49       200



In [117]:
clf2 = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

clf2.fit(x_train, y_train)
y_pred = clf2.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.76      0.78        96
           1       0.79      0.82      0.80       104

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.79       200
weighted avg       0.79      0.79      0.79       200

